=== Medvetojas/university-courses/XML/XMLTaskA6NQW1/XMLSchemaA6NQW1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">

    <!-- Elemek, tulajdonságok -->

    <xs:element name="telepules" type="xs:string" />
    <xs:element name="fizetes" type="xs:integer" />
    <xs:element name="ledolgozott_evek" type="xs:integer" />
    <xs:element name="sebesseghatar" type="xs:integer" />
    <xs:element name="osszeg" type="xs:integer" />
    <xs:element name="rendszam" type="xs:string" />
    <xs:element name="varos" type="xs:string" />
    <xs:element name="lakcim" type="xs:string" />

    <xs:attribute name="AF_ID" type="xs:integer" />
    <xs:attribute name="AF_IDREF" type="xs:integer" />
    <xs:attribute name="AL_ID" type="xs:integer" />
    <xs:attribute name="AL_IDREF" type="xs:integer" />
    <xs:attribute name="AU_ID" type="xs:integer" />
    <xs:attribute name="AU_IDREF" type="xs:integer" />
    <xs:attribute name="T_ID" type="xs:integer" />
    <xs:attribute name="B_ID" type="xs:integer" />
    <xs:attribute name="B_IDREF" type="xs:integer" />
    <xs:attribute name="SZ_ID" type="xs:integer" />

    <!-- Egyszerű típusok -->

    <xs:simpleType name="datum_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="(19|20)\d\d.(0[1-9]|1[012]).(0[1-9]|[12][0-9]|3[01])"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="iranyitoszam_type">
        <xs:restriction base="xs:string">
          <xs:length value="4" />
          <xs:pattern value="([0-9])*" />
        </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="megnevezes_type">
        <xs:restriction base="xs:string">
          <xs:minLength value="1" />
          <xs:pattern value="([a-zA-Z][0-9])*" />
        </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="nev_type">
        <xs:restriction base="xs:string">
          <xs:pattern value="[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)*" />
        </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="sebesseghatar_type">
        <xs:restriction base="xs:string">
          <xs:maxLength value="3" />
          <xs:pattern value="([0-9])*" />
        </xs:restriction>
      </xs:simpleType>


    <!-- Komplex típusok -->

    <xs:complexType name="autopalya_felugyelet_tipus">
        <xs:sequence>
            <xs:element ref="telepules"/>
        </xs:sequence>
        <xs:attribute ref="AF_ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="alkalmazott_tipus">
        <xs:sequence>
            <xs:element ref="fizetes"/>
            <xs:element ref="ledolgozott_evek"/>
        </xs:sequence>
        <xs:attribute ref="AL_ID" use="required"/>
        <xs:attribute ref="AF_IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="autopalya_tipus">
        <xs:sequence>
            <xs:element name="megnevezes" type="megnevezes_type"/>
        </xs:sequence>
        <xs:attribute ref="AU_ID" use="required"/>
        <xs:attribute ref="AF_IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="traffipax_tipus">
        <xs:sequence>
            <xs:element ref="sebesseghatar"/>
        </xs:sequence>
        <xs:attribute ref="T_ID" use="required"/>
        <xs:attribute ref="AU_IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="buntetes_tipus">
        <xs:sequence>
            <xs:element ref="osszeg"/>
            <xs:element name="datum" type="datum_type"/>
        </xs:sequence>
        <xs:attribute ref="B_ID" use="required"/>
        <xs:attribute ref="AF_IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="elerhetoseg_tipus">
        <xs:sequence>
            <xs:element name="nev" type="nev_type"/>
            <xs:element name="iranyitoszam" type="iranyitoszam_type"/>
            <xs:element ref="varos"/>
            <xs:element ref="lakcim"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="szabalyserto_tipus">
        <xs:sequence>
            <xs:element ref="rendszam"/>
            <xs:element name="elerhetoseg" type="elerhetoseg_tipus"/>
        </xs:sequence>
        <xs:attribute ref="SZ_ID" use="required"/>
        <xs:attribute ref="B_IDREF" use="required"/>
    </xs:complexType>

    <!-- Kiszabott büntetések -->

    <xs:element name="gyorsforgalmi_rendszer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="autopalya_felugyelet" type="autopalya_felugyelet_tipus" maxOccurs="unbounded"/>
                <xs:element name="alkalmazott" type="alkalmazott_tipus" maxOccurs="unbounded"/>
                <xs:element name="autopalya" type="autopalya_tipus" maxOccurs="unbounded"/>
                <xs:element name="traffipax" type="traffipax_tipus" maxOccurs="unbounded"/>
                <xs:element name="buntetes" type="buntetes_tipus" maxOccurs="unbounded"/>
                <xs:element name="szabalyserto" type="szabalyserto_tipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Kulcsok -->

        <xs:unique name="AF_ID">
            <xs:selector xpath="autopalya_felugyelet"/>
            <xs:field xpath="@AF_ID"/>
        </xs:unique>

        <xs:key name="AL_ID">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@AL_ID"/>
        </xs:key>

        <xs:key name="AU_ID">
            <xs:selector xpath="autopalya"/>
            <xs:field xpath="@AU_ID"/>
        </xs:key>

        <xs:unique name="T_ID">
            <xs:selector xpath="traffipax"/>
            <xs:field xpath="@T_ID"/>
        </xs:unique>

        <xs:key name="B_ID">
            <xs:selector xpath="buntetes"/>
            <xs:field xpath="@B_ID"/>
        </xs:key>

        <xs:key name="SZ_ID">
            <xs:selector xpath="szabalyserto"/>
            <xs:field xpath="@SZ_ID"/>
        </xs:key>

        <!-- Kulcshivatkozások (idegen kulcsok) -->

        <xs:keyref name="autopalya_felugyelet_FK1" refer="AF_ID">
            <xs:selector xpath="alkalmazott"></xs:selector>
            <xs:field xpath="@AF_IDREF"></xs:field>
        </xs:keyref>

        <xs:keyref name="autopalya_felugyelet_FK2" refer="AF_ID">
            <xs:selector xpath="autopalya"></xs:selector>
            <xs:field xpath="@AF_IDREF"></xs:field>
        </xs:keyref>

        <xs:keyref name="autopalya_felugyelet_FK3" refer="AF_ID">
            <xs:selector xpath="buntetes"></xs:selector>
            <xs:field xpath="@AF_IDREF"></xs:field>
        </xs:keyref>

        <xs:keyref name="autopalya_FK1" refer="AU_ID">
            <xs:selector xpath="traffipax"></xs:selector>
            <xs:field xpath="@AU_IDREF"></xs:field>
        </xs:keyref>

        <xs:keyref name="buntetes_FK1" refer="B_ID">
            <xs:selector xpath="szabalyserto"></xs:selector>
            <xs:field xpath="@B_IDREF"></xs:field>
        </xs:keyref>

    </xs:element>

</xs:schema>

=== Medvetojas/university-courses/XML/XMLTaskA6NQW1/DOMParseA6NQW1/XMLA6NQW1.xml
<?xml version="1.0" encoding="UTF-8"?>

<gyorsforgalmi_rendszer xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaA6NQW1.xsd">

    <!-- Autópálya Felügyeletek -->

    <autopalya_felugyelet AF_ID="1">
        <telepules>Budapest</telepules>
    </autopalya_felugyelet>

    <autopalya_felugyelet AF_ID="2">
        <telepules>Miskolc</telepules>
    </autopalya_felugyelet>

    <autopalya_felugyelet AF_ID="3">
        <telepules>Miskolc</telepules>
    </autopalya_felugyelet>

    <autopalya_felugyelet AF_ID="4">
        <telepules>Vásárosnamény</telepules>
    </autopalya_felugyelet>

    <autopalya_felugyelet AF_ID="5">
        <telepules>Törökbálint</telepules>
    </autopalya_felugyelet>

    <!-- Alkalmazottak -->

    <alkalmazott AL_ID="1" AF_IDREF="1">
        <fizetes>650000</fizetes>
        <ledolgozott_evek>5</ledolgozott_evek>
    </alkalmazott>

    <alkalmazott AL_ID="2" AF_IDREF="4">
        <fizetes>180000</fizetes>
        <ledolgozott_evek>1</ledolgozott_evek>
    </alkalmazott>

    <alkalmazott AL_ID="3" AF_IDREF="2">
        <fizetes>1520000</fizetes>
        <ledolgozott_evek>12</ledolgozott_evek>
    </alkalmazott>

    <alkalmazott AL_ID="4" AF_IDREF="5">
        <fizetes>800000</fizetes>
        <ledolgozott_evek>8</ledolgozott_evek>
    </alkalmazott>

    <alkalmazott AL_ID="5" AF_IDREF="1">
        <fizetes>0</fizetes>
        <ledolgozott_evek>1</ledolgozott_evek>
    </alkalmazott>

    <alkalmazott AL_ID="6" AF_IDREF="3">
        <fizetes>420000</fizetes>
        <ledolgozott_evek>4</ledolgozott_evek>
    </alkalmazott>

    <!-- Autópályák -->

    <autopalya AU_ID="1" AF_IDREF="1">
        <megnevezes>M0</megnevezes>
    </autopalya>

    <autopalya AU_ID="2" AF_IDREF="2">
        <megnevezes>M3</megnevezes>
    </autopalya>

    <autopalya AU_ID="3" AF_IDREF="5">
        <megnevezes>M5</megnevezes>
    </autopalya>

    <autopalya AU_ID="4" AF_IDREF="1">
        <megnevezes>M9</megnevezes>
    </autopalya>

    <autopalya AU_ID="5" AF_IDREF="4">
        <megnevezes>M34</megnevezes>
    </autopalya>

    <autopalya AU_ID="6" AF_IDREF="3">
        <megnevezes>M9</megnevezes>
    </autopalya>

    <!-- Sebességmérő kamerák -->

    <traffipax T_ID="1" AU_IDREF="3">
        <sebesseghatar>130</sebesseghatar>
    </traffipax>

    <traffipax T_ID="2" AU_IDREF="2">
        <sebesseghatar>90</sebesseghatar>
    </traffipax>

    <traffipax T_ID="3" AU_IDREF="5">
        <sebesseghatar>110</sebesseghatar>
    </traffipax>

    <traffipax T_ID="4" AU_IDREF="1">
        <sebesseghatar>130</sebesseghatar>
    </traffipax>

    <traffipax T_ID="5" AU_IDREF="6">
        <sebesseghatar>90</sebesseghatar>
    </traffipax>

    <traffipax T_ID="6" AU_IDREF="6">
        <sebesseghatar>130</sebesseghatar>
    </traffipax>

    <traffipax T_ID="7" AU_IDREF="4">
        <sebesseghatar>110</sebesseghatar>
    </traffipax>

    <!-- Kiszabott büntetések -->

    <buntetes B_ID="1" AF_IDREF="1">
        <osszeg>50000</osszeg>
        <datum>2022-03-02</datum>
    </buntetes>

    <buntetes B_ID="2" AF_IDREF="2">
        <osszeg>30000</osszeg>
        <datum>2021-12-10</datum>
    </buntetes>

    <buntetes B_ID="3" AF_IDREF="4">
        <osszeg>200000</osszeg>
        <datum>2020-11-20</datum>
    </buntetes>

    <buntetes B_ID="4" AF_IDREF="3">
        <osszeg>100000</osszeg>
        <datum>2019-06-15</datum>
    </buntetes>

    <buntetes B_ID="5" AF_IDREF="5">
        <osszeg>20000</osszeg>
        <datum>2021-01-01</datum>
    </buntetes>

    <!-- Szabálysértők és az adataik -->

    <szabalyserto SZ_ID="1" B_IDREF="1">
        <rendszam>TXT-637</rendszam>
        <elerhetoseg>
            <nev>Trab Antal</nev>
            <iranyitoszam>7542</iranyitoszam>
            <varos>Kisbajom</varos>
            <lakcim>Eötvös út 63</lakcim>
        </elerhetoseg>
    </szabalyserto>

    <szabalyserto SZ_ID="2" B_IDREF="2">
        <rendszam>GFD-874</rendszam>
        <elerhetoseg>
            <nev>Para Zita</nev>
            <iranyitoszam>8477</iranyitoszam>
            <varos>Veszprém</varos>
            <lakcim>Izabella utca 15 2/6</lakcim>
        </elerhetoseg>
    </szabalyserto>

    <szabalyserto SZ_ID="3" B_IDREF="3">
        <rendszam>HGF-321</rendszam>
        <elerhetoseg>
            <nev>Patta Nóra</nev>
            <iranyitoszam>2454</iranyitoszam>
            <varos>Iváncsa</varos>
            <lakcim>Erzsébet krt 43</lakcim>
        </elerhetoseg>
    </szabalyserto>

    <szabalyserto SZ_ID="4" B_IDREF="4">
        <rendszam>FSD-415</rendszam>
        <elerhetoseg>
            <nev>Fá Zoltán</nev>
            <iranyitoszam>4972</iranyitoszam>
            <varos>Gacsály</varos>
            <lakcim>Apor Péter utca 10</lakcim>
        </elerhetoseg>
    </szabalyserto>

    <szabalyserto SZ_ID="5" B_IDREF="5">
        <rendszam>UZR-543</rendszam>
        <elerhetoseg>
            <nev>Remek Elek</nev>
            <iranyitoszam>8692</iranyitoszam>
            <varos>Szőlősgyörök</varos>
            <lakcim>Bécsi utca 93</lakcim>
        </elerhetoseg>
    </szabalyserto>

</gyorsforgalmi_rendszer>
